### ISSUE TITLE
Easier publishing

### ISSUE THREAD

**Issue by heruku** [dirv/pinaclj#19]
In order to publish a page the user must write a timestamp in a the ISO_INSTANT format: `2014-10-31T10:05:00Z`

Here are my ideas  to make it easier:
  * parse the timestamp more leniently handling all of these: `2014-10-31`, `31-10-2014`, `31.10.2014` (rails like magic parsing)
  * provide a configuration to specify format
  * provide a cli publisher: `pinaclj publish drafts/post.md`. It would automatically add current date as a published-at header.

**Comment by dirv** [comment]
I like options #1 and #3. I was thinking of #3 but #1 would probably fit more into the work flow you want?

**Comment by dirv** [comment]
1 would be the simpler thing to do right now.

**Comment by dirv** [comment]
Third option was implemented
